spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: quiz-platform
  datasource:
    url: jdbc:h2:mem:quizdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    com.quizplatform: DEBUG